name: Build and Release

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release

    - name: Package Release
      if: startsWith(github.ref, 'refs/tags/v')
      shell: bash
      run: |
        cd ${{github.workspace}}/build
        cp ../nn-62ef826d1a6d.nnue .
        if [ "$RUNNER_OS" == "Windows" ]; then
          if [ -f "Release/BlunderBot.exe" ]; then
            cp Release/BlunderBot.exe .
          fi
          7z a BlunderBot-${{ matrix.os }}.zip BlunderBot.exe nn-62ef826d1a6d.nnue
        else
          zip -r BlunderBot-${{ matrix.os }}.zip BlunderBot nn-62ef826d1a6d.nnue
        fi

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: ${{github.workspace}}/build/BlunderBot-${{ matrix.os }}.zip
