name: Smoke Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  smoke-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ubuntu-latest-ccache-${{ github.ref }}
        restore-keys: |
          ubuntu-latest-ccache-

    - name: Configure CMake with ASAN
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_FLAGS="-fsanitize=address -g -O2" -DCMAKE_C_FLAGS="-fsanitize=address -g -O2" -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=address"

    - name: Build Engine
      run: cmake --build ${{github.workspace}}/build --config Release

    - name: Generate Opening Book
      shell: bash
      working-directory: build
      run: ./make_book ../data/openings.txt blunderbot_book.bin

    - name: Run Smoke Test
      run: |
        python3 tests/smoke_test.py

    - name: Run Perft Test
      run: |
        python3 tests/perft_test.py
